CREATE DATABASE smsApplication;

use smsApplication;

CREATE TABLE IF NOT EXISTS accounts(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
OrganisationName VARCHAR(255) NOT NULL,
phone INT NOT NULL,
Email VARCHAR(255) NOT NULL,
AccountLocation VARCHAR(255) NOT NULL,
AccountType VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserOrgId INT NOT NULL,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
Phone INT NOT NULL,
FOREIGN KEY (UserOrgId) REFERENCES accounts(ID)
);

CREATE TABLE IF NOT EXISTS categories(
CatID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CatOrgId INT NOT NULL,
Name VARCHAR(255) NOT NULL,
Description TEXT NOT NULL,
FOREIGN KEY (CatOrgId) REFERENCES accounts(ID)
);

CREATE TABLE IF NOT EXISTS contacts(
ContID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ContCatID INT NOT NULL,
ContPhone INT NOT NULL,
ContName VARCHAR(255) NOT NULL,
ContCreator VARCHAR(255) NOT NULL,
ContEmail VARCHAR(255) NOT NULL,
FOREIGN KEY (ContCatID) REFERENCES categories(CatID),
FOREIGN KEY (ContCreator) REFERENCES users(UserID)
);

CREATE TABLE IF NOT EXISTS messages(
MsgID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
MsgPhone INT NOT NULL,
MsgText TEXT NOT NULL,
MsgCreateTime TIMESTAMP,
MsgSender INT NOT NULL,
FOREIGN KEY (MsgSender) REFERENCES users(userID)
);